version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
      - npm sonar:sonar -Dsonar.login=d7063144e831c0f8e214c21e4a13afaa97beb67e -Dsonar.host.url=http://18.220.196.198:9000
